### PR TITLE
Add archiving branches as part of cleanup

### PR DESCRIPTION
**Pull request by adamsilverstein**
### Proposing
* Archive branches as part of cleanup flow when deleting them.
* add exact git commands to clarify what should happen

### Benefits
Keeping an archive of merged branch as tag captures makes restoring branches much easier should the need arise and simplifies some repository forensics, eg tracking down specific commits from a squashed merge.

### CODE REVIEW

**Comment by nicholasio** [comment]
Not so long ago we decided that archiving branches did not make sense anymore: https://github.com/10up/Engineering-Best-Practices/issues/185. I believe the main takeaway was that, the need for archiving branches would not make sense for most of the projects and it is still possible to restore code and track down commits even without tags.

**Comment by ericmann** [comment]
As @nicholasio points out, this effectively reverts the changes introduced by #188 (explanation in #185). Feels like a move backwards in the quality of the documentation.

> Keeping an archive of merged branch as tag captures makes restoring branches much easier should the need arise 

Using non-fast-forward merges provides the same benefit without cluttering the tag list for a project.

> simplifies some repository forensics, eg tracking down specific commits from a squashed merge

Unless I'm missing something, squashed merges are already discouraged in the workflows section: https://10up.github.io/Engineering-Best-Practices/version-control/#merges

**Comment by ryanwelcher** [comment]
Whether or not archiving branches is needed is going to be situational. In general, 10up doesn't do it anymore but that doesn't mean that other teams using this document have the same view. 

Perhaps this becomes a best practice on how to archive effectively if the choice is made to do so rather than prescribing if they should or not.

I like the idea of adding git commands, it may not be clear how to get a branch back from either a tag or merge commit.

**Comment by ericmann** [comment]
> In general, 10up doesn't do it anymore but that doesn't mean that other teams using this document have the same view.

Archiving was only a practice at 10up because of a specific project and team that needed it. I was the one who came up with the practice at the time and originally standardized it in the docs here. It only ever made sense then for a _super_ limited use case and.

That's why we _removed_ it in the aforementioned issues and commits.

> I like the idea of adding git commands, it may not be clear how to get a branch back from either a tag or merge commit.

General guidance on using Git to create a new branch based on a merge commit or a tag would be useful, but should definitely be in a different section.

**Comment by adamsilverstein** [comment]
Thanks for the feedback @nicholasio and @ericmann - I missed the previous discussion - happy to withdraw or rework the proposal if the original thinking still stands.

I brought this up after _working on the several projects where squash merges were explicitly required_ (see: Gutenberg). Squashed commits are excellent for keeping the commit history in master clean, and tagging branches seems like a simple way to maintain the branch history at the same time. 

> Using non-fast-forward merges provides the same benefit without cluttering the tag list for a project.

Right, so maybe we can explicitly say this is for when not using fast-forward. I don't understand why "cluttering the tag list" is an issue.

**Review by ryanwelcher — APPROVED** [review]

**Comment by adamsilverstein** [comment]
@ericmann @ryanwelcher @nicholasio -

Updated PR clarifying when deleting and arching might be appropriate, and why. What do you think?

**Comment by ericmann** [comment]
> I don't understand why "cluttering the tag list" is an issue.

I use the command line, so I don't care about clutter. Large tag lists, however, have crashed GUI based utilities other engineers use, particularly on large projects. Tags should be used to, you know, _tag commits_ with some specific meaning. A reference to a release, to production or otherwise, for example.

They provide meaningful context and should continue to do so. Creating a tag because of a merge is an antipattern that I 100% regret ever having suggested.

> What do you think?

At this stage, it's entirely up to you and the team. I came up with "archived branches" as a workflow to appease non-technical stakeholders on a specific VIP project. We codified it at the time because there were similarly less-than-technical engineers on the team who didn't fully understand version control. We removed the practice from the docs later because it never made sense in the first place and removing it was a good idea.

I think I've said more than enough here and am officially backing out of this conversation.

**Comment by adamsilverstein** [comment]
> Tags should be used to, you know, tag commits with some specific meaning.

Archiving a branch before deleting it does just that: it creates a commit with a specific meaning: the branch being deleted and its commit history

> I came up with "archived branches" as a workflow to appease non-technical stakeholders on a specific VIP project

I appreciate that you regret having proposed this as a best practice :) I still think it makes sense in certain cases (the two main projects I am working on both use a squashed commit merge strategy) as explained in my PR. I've also seen archiving strategies used on other projects in non-10up contexts.

Thanks for your feedback and the historical context.

**Review by nicholasio — COMMENTED** [review]
I haven't worked on a squash and merge workflow yet, but after reading a bit more about the workflow I can see a few benefits and I can see tagged branches being valuable mainly to keep the commit history.

I'm ok with this since is imposing the tagging workflow only for squash and merge workflow.

But before we merge this, @adamsilverstein what do you think about adding some guidance on when to use `--no-ff` versus `squash and merge`? I don't think we mention the squash and merge workflow anywhere in our docs

**Comment by ryanwelcher** [comment]
I like this approach @adamsilverstein. I think we need to be careful to provide guidance in a Best Practice doc and not be too prescriptive. If there is a need to archive branches, now we have a recommended way to handle it.

We're not saying that doing so is the best approach, we're just providing guidance based on our experiences doing so.

**Comment by adamsilverstein** [comment]
> But before we merge this, @adamsilverstein what do you think about adding some guidance on when to use --no-ff versus squash and merge? I don't think we mention the squash and merge workflow anywhere in our docs

That seems useful, summarizing pros/cons of each approach; thanks for the suggestion. 

I am going to start by opening an issue to add that information so I can get this merged and solicit wider feedback on squash vs. -no-ff

**Pull request merged**
