### PR TITLE
Update Commit message best practices

### LINKED ISSUE #109: Commit message best practices
I just published [best practices for commit messages in WordPress core](https://make.wordpress.org/core/handbook/best-practices/commit-messages/), much of which is general commit message advice. This is mostly a placeholder issue so we add this to our own best practices at 10up, with some blog posts I plan on writing to go along with it.

### PR DESCRIPTION
**Pull request by jonathantneal**
This gives everyone advice for writing commit messages. It borrows heavily from and resolves #109.

### CODE REVIEW

**Comment by helen** [comment]
This is a good start. I think it would be good to include more about how one goes about deciding how much detail to include, e.g. a typical, hopefully-atomic commit while working on something vs. a merge.

**Comment by tlovett1** [comment]
I'd also like to see expectations set on what is required. I think we require the short description but not the long one.

**Comment by jonathantneal** [comment]
I’ve re-written this section to be simpler to read and more clear about our expectations, including examples of quality commit messages alongside our advice.

**Comment by dana-ross** [comment]
Thanks @jonathantneal . Love the examples. I know I'm definitely guilty of blowing past the 70 character limit & spilling details into the commit message.

On that note, maybe add a warning against using the `git -m` command line option?

**Comment by jonathantneal** [comment]
@daveross, I think `-m` has it’s place, and my examples show how and when to use `git commit` with or without the `-m` option. Thanks for the kind review, btw. @tlovett1, is this yet merge-worthy?

**Comment by tlovett1** [comment]
Looks solid to me.

**Pull request merged**
