### PR TITLE
Feature/mobile adjustments

### PR DESCRIPTION
**Pull request by saltcod**
It occurred to me after I opened that h3 style ticket that most of what I've done today is pretty subjective. So here's the rest of it. Mostly addresses spacing / padding / margin issues on mobile, but also makes a bunch of font adjustments. 

I'm new, new, new to this so 1000 apologies for likely doing this the wrong way!   =)

### CODE REVIEW

**Comment by saltcod** [comment]
Hummmm so ....I can keep adding to this pull request?  I probably shouldn't though (?). 

Anyway, the last commit here addresses an issue with the menu at in-between window sizes. As it is now, the toggled menu needs to be invoked earlier to avoid the main nav menu jumping to the next line as per the screen. Another solution would be to progressively drop the last n items as the screen gets narrower. I like this approach sometimes. 

hamburgler

**Comment by jonbellah** [comment]
The issue in your screenshot is addressed in https://github.com/10up/Engineering-Best-Practices/pull/76

**Comment by tlovett1** [comment]
Can you guys coordinate on these PRs?

**Comment by tlovett1** [comment]
Any update on this?

**Comment by tlovett1** [comment]
Closing. Feel free to reopen if still relevant.

**Pull request closed without merging**
