### PR TITLE
Nonces: replay attacks and nonces tied to action and unique id

### PR DESCRIPTION
**Pull request by ivankruchkoff**
Address #123

### CODE REVIEW

**Comment by tlovett1** [comment]
It would be nice to get some more clarification on "unique" vs. non-unique nonces.

**Comment by dana-ross** [comment]
> WordPress' implementation of nonces are not strictly numbers...
> 
> The WordPress definition of nonces is "A cryptographic token...

@ivankruchkoff I think these paragraphs are similar enough they should be combined. That would also give a good opportunity to clarify how WP nonces don't necessarily _prevent_ replay attacks, but they _do_ limit the window of time for them. The difference might not be immediately obvious.

**Comment by tlovett1** [comment]
Any update here?

**Comment by timwright12** [comment]
@ivankruchkoff Is this still active or should we close it out?

**Pull request closed without merging**
