### PR TITLE
Add switch_to_blog limitation

### PR DESCRIPTION
**Pull request by kierahowe**
I thought it would be good to mention that switch_to_blog is generally a bad idea on the front-end and is a performance issue if used.

### CODE REVIEW

**Comment by nicholasio** [comment]
Last time and checked on this, the biggest problem was more memory consumption that the query itself, I also know that there were major improvements to this function after the initial concerns regarding its performance. I agree that we should generally discourage the use of this function but there are times when it becomes really handy and useful (our Distributor plugin is an example). In my opinion we should, instead of saying "never use this function" say that it's important to have a cache strategy in place and use this function wisely.  For examples I've seen code that does several switch/restore before each template tag function when it could just do one switch/restore and have all functions be called inside that block. We should also recommend pursing other solutions first like REST API if all it's needed is to get content from other sites.

**Comment by tlovett1** [comment]
Awesome start, @kierahowe! Definitely agree with @nicholasio there are use cases where this is necessary and we should provide some best practices around those. I'd also love to see some info on why this isn't performant.

**Comment by kierahowe** [comment]
Okay... Sounds good.   I will rework this a bit to a "recommend not using it" with a couple of alternatives and details why it isn't performant.

**Comment by timwright12** [comment]
@kierahowe @nicholasio Any update here?

**Comment by nicholasio** [comment]
@timwright12 no but if you assign this one to me I can work on it.

**Pull request closed without merging**
