### PR TITLE
Syntax and Standards fixes for PHP Code Examples

### PR DESCRIPTION
**Pull request by rachelbaker**

### CODE REVIEW

**Comment by DrewAPicture** [comment]
I'd like to see docblocks added to our example functions as well. I'm happy to do it if there's agreement.

**Comment by rachelbaker** [comment]
@DrewAPicture YES, please.  But get your own issue for that, and don't bogart mine :kissing_cat:

**Comment by DrewAPicture** [comment]
Seeing as docs fall under standards, I'd say it applies. But I'm picking up what you're laying down :)

**Comment by rachelbaker** [comment]
@DrewAPicture I did open the door by going outside of #22's narrow scope and adding in spacing adjustments.  You are correct, that docs fall under standards.  

This PR is sourced from my fork.  Which means that really the best course of action here is to have a new issue (or PR) specific to the code standardization of our examples.

**Comment by tlovett1** [comment]
Looks good. Agree, separate PR.

**Pull request merged**
