### PR TITLE
Update margin on the 6th menu item to prevent logo overlapping

### PR DESCRIPTION
**Pull request by dmtrmrv**
### Description of the Change

This PR fixes an issue with overlapping the logo with Design menu item

### Alternate Designs

n/a

### Benefits

Fixes the visual regression.

### Possible Drawbacks

None identified

### Verification Process

Tested the header appearance across different screen sizes.

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

n/a

### Changelog Entry

Fixed visual regression in the navigation

### CODE REVIEW

**Comment by jeffpaul** [comment]
@dmtrmrv is this similar to https://github.com/10up/Engineering-Best-Practices/pull/349?

**Review by tylercherpak — APPROVED** [review]

**Comment by smy315** [comment]
@dmtrmrv if you have time this week, want to work on a complete fix? System (last menu item) cuts off at some breakpoints (with and without your update):

Screen Shot 2021-01-19 at 10 08 35 AM

Also, extra space after PHP and 10up logo (with and without the update on this PR):

Screen Shot 2021-01-19 at 10 09 33 AM

@jeffpaul referenced https://github.com/10up/Engineering-Best-Practices/pull/352#issuecomment-760603085 so some of this work might have been done already by Michele. Maybe close out this branch and look over Michele's work?

**Comment by joesnellpdx** [comment]
Closing this branch as issue was resolved here: https://github.com/10up/Engineering-Best-Practices/pull/349

**Comment by joesnellpdx** [comment]
Closing this PR as issue was resolved here: #349

**Pull request closed without merging**
