### PR TITLE
Fix headings in correct order

### PR DESCRIPTION
**Pull request by RachelRVasquez**

### CODE REVIEW

**Comment by tlovett1** [comment]
There are some conflicts to resolve. Also, we tinkered a bunch with the headings - not sure if it makes sense to continue.

**Comment by RachelRVasquez** [comment]
@tlovett1 Conflicts have been resolved. Up to you if you want to merge - at least this way, our best practices follow semantic heading heirarchy versus skipping levels. I use this [Chrome extension](https://chrome.google.com/webstore/detail/headingsmap/flbjommegcjonpdmenkdiocclhjacmbi?hl=en) to help me see the heading structure at a glance, comes in handy.

**Comment by tlovett1** [comment]
Is this still applicable?

**Comment by RachelRVasquez** [comment]
Should be up to date now. 👍

**Pull request merged**
