### PR TITLE
Add a configuration best practices page

### PR DESCRIPTION
**Pull request by nprasath002**
Related https://github.com/10up/Engineering-Best-Practices/issues/74

This is a blank configuration page and a work in progress PR to get early feedback. First addition would be defining `IMAGE_EDIT_OVERWRITE ` to save disk space

### CODE REVIEW

**Comment by tlovett1** [comment]
I could see a place for this. `IMAGE_EDIT_OVERWRITE` makes sense. Wondering what else you had in mind? Would also love to hear other opinions. Thanks for bringing up the topic!

**Comment by benoitchantre** [comment]
- `DISALLOW_FILE_EDIT`: prevent unwanted changes
- `WP_POST_REVISIONS`: limit or disable revisions for performance reasons
- `FORCE_SSL_ADMIN`: force secure connections to the admin and login page
- `/%postname%/` as [permalink structure](https://yoast.com/wordpress-seo-url-permalink/)
- `DISABLE_WP_CRON ` in favor of real cron jobs

Eventually:
- useful custom roles
- security hardening
- root install vs subdirectory install (pros and cons)
- caching strategies

The configuration page could have two sections:

1. development
1. production

Will the configuration best practices limited to WordPress itself?
The page could include some recommendations for Apache and Nginx.

**Comment by benoitchantre** [comment]
Other ideas:
- keep credentials in a separated file from wp-config.php
- use .gitignore to keep credentials outside of the repository
- define an environment variable to customize the behavior of your site depending of the environment (e.g. payment gateways have to use sandbox mode except on production environment)

Inspired by [Tips for configuring WordPress environments](https://markjaquith.wordpress.com/2018/02/05/tips-for-configuring-wordpress-environments/) (Mark Jaquith) and [Configuring wp-config.php](https://pantheon.io/docs/wp-config-php/) from Pantheon

**Comment by plasticmind** [comment]
Not sure if this makes sense to include, but I've recently started putting credentials in the Apache httpd.conf:

```
<VirtualHost>

# Environment variables
SetEnv WP_HOME _http://example.com_

# Database variables
SetEnv DB_NAME *database_name_here*
SetEnv DB_USER *username_here*
SetEnv DB_PASSWORD *password_here*
SetEnv DB_HOST localhost
SetEnv DB_PREFIX wp_
SetEnv DB_CHARSET utf8mb4

# Keys and Salts
SetEnv AUTH_KEY 'put your unique phrase here'
SetEnv SECURE_AUTH_KEY 'put your unique phrase here'
SetEnv LOGGED_IN_KEY 'put your unique phrase here'
SetEnv NONCE_KEY 'put your unique phrase here'
SetEnv AUTH_SALT 'put your unique phrase here'
SetEnv SECURE_AUTH_SALT 'put your unique phrase here'
SetEnv LOGGED_IN_SALT 'put your unique phrase here'
SetEnv NONCE_SALT 'put your unique phrase here'

</VirtualHost>
```

Then pulled the variable into wp-config.php accordingly:

```
define('DB_NAME', getenv('DB_NAME'));
```

This can be a little tricky to implement on some environments, so I've allowed local overrides by doing something like this in the wp-config.php:

```
/** Allow custom configuration overrides for local development. */
if ( file_exists( ABSPATH . 'wp-config.local.php' ) ) {
	require_once ( ABSPATH . 'wp-config.local.php' );
}
// ** MySQL settings - Sensitive credentials are stored as Apache environment variables ** //
/** The name of the database for WordPress */
if ( !defined('DB_NAME') )
	define('DB_NAME', getenv('DB_NAME'));
```

That allows credentials to either be stored in the Apache host file (on production environments) or in a wp-config.local.php (on local environments) which gets added to .gitignore.

**Comment by tlovett1** [comment]
I definitely think there could be something here. Just need to flesh out the PR a bit more.

As for Apache, we don't typically use it.

**Pull request closed without merging**
