### PR TITLE
Updated package management documentation

### PR DESCRIPTION
**Pull request by timwright12**
Updated NPM with documentation instructions per our internal conversation.

### CODE REVIEW

**Comment by dana-ross** [comment]
I know we've discussed our differences here, but this is from the co-founder & COO of npm, Inc.

> npm is always lowercase. The tool is not called NPM. The company is not called NPM, Inc.. It's always just npm.

https://twitter.com/seldo/status/850042251635867648?s=20

**Comment by timwright12** [comment]
:groan:

**Comment by timwright12** [comment]
@daveross lowercased npm throughout the docs

**Comment by dana-ross** [comment]
Wouldn't we also use npm for managing dependencies for the rare node.js project?

**Comment by nicholasio** [comment]
@daveross  maybe say we use npm for dependencies (without explicitly saying it's for frontend dependencies).

**Comment by timwright12** [comment]
@nicholasio there's a little toe-stepping with Composer if we don't specify something IMO. How about "relevant dependencies"? @daveross That should cover, JS, non-JS, testing, and Node stuff.

**Comment by timwright12** [comment]
Updated

**Comment by dana-ross** [comment]
👍

**Pull request merged**
