### PR TITLE
First stab at a note on heredoc/nowdoc syntax ( issue #92 )

### PR DESCRIPTION
**Pull request by dana-ross**
Collaborated with @scottlee on this. Feedback/edits welcome.

### CODE REVIEW

**Comment by tlovett1** [comment]
I think this looks great. Not sure how I feel about the `get_template_part` section though. I think we should be using that a bit more judiciously. I'm not a fan of opening a theme to find 30 template partials. Thoughts?

**Comment by ericmann** [comment]
As much as I don't like having to grok lots of template partials, dividing the theme itself up into multiple, purpose-specific partials does make sense (particularly if they're re-usable).

Usually, the argument for a heredoc/nowdoc block is that it's a chunk of HTML (or other non-PHP) code that needs to be reused elsewhere. That's the same reason we break out smaller template parts. Some VIP sites we've worked on have rich template directories with over 100 different template partials (due to the way we've broken the site down into individually-styled, standalone, reusable components).

So I can totally see the use of `get_template_part()` in place of heredoc/nowdoc syntax for large chunks of markup. I think either presenting or linking to an example of how that can be achieved would make the advice even stronger.

**Comment by dana-ross** [comment]
@tlovett1 @ericmann What do you think, should we merge this? Happy to take out the get_template_part() section if that's a sticking point.

**Comment by tlovett1** [comment]
I'm good with this.

**Pull request merged**
